---
title: Jose Vte Esteve.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: JoseVteEsteve
description: Blog sobre informatica, ciencia y educación
avatar: https://avatars1.githubusercontent.com/u/39584994?s=460&v=4
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: JoseVteEsteve
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: JoseVteEsteve
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: 
google_analytics: 
url: http://bit.ly/cs4u2
baseurl: ''
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
remote_theme: Leaf
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
